### LAB 3
### HRITIK AJAY BANSAL
### CSE A 15, 180905105

# Practice Questions


In [3]:
import numpy as np
a=np.array([1,2,3,4,5])
a.dtype


dtype('int64')

In [4]:
b=np.array([1.2,22,3.445,6])
b.dtype

dtype('float64')

In [7]:
a=np.array([(1,2,3),(4,5,6)])
a #two dimentional array

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
s=np.arange(10,20,2)
s #STARTING STEPSIZE THEN ENDING LIMIT, NOT INCLUDED

array([10, 12, 14, 16, 18])

In [14]:
s=np.arange(1,2,0.1)
s

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [16]:
s1=np.linspace(10,20,7) # produce 7 numbers starting 10 & ends with 20
s1

array([10.        , 11.66666667, 13.33333333, 15.        , 16.66666667,
       18.33333333, 20.        ])

In [23]:
import random as r
r.choice([1,2,3,4,5])



5

In [20]:
r.choice("hritik")

'r'

In [22]:
r.randrange(12,45)

44

In [24]:
r.random()

0.18551823844764936

In [26]:
r.uniform(5,10)

8.062443419906774

In [30]:
c=[1,2,3,4,5]
r.shuffle(c)
c

[1, 3, 5, 2, 4]

In [39]:
a=r.seed(10)
print(a)

None


In [45]:
#2d matrix
a=np.arange(15)
print(a)
print("\n2 d\n")
a=a.reshape(3,5)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

2 d

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [62]:
#3d matrix
c=np.arange(24).reshape(2,3,4)
print(c)
print()
print(c[1,:,:])
print()
print(c[:,:,2])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

[[ 2  6 10]
 [14 18 22]]


In [55]:
# array operations
a=np.array([10,20,30,40])
b=np.arange(4)
print(b)
c=a-b
print(c)

print(b**2)

print(10*np.sin(a))

a<35


[0 1 2 3]
[10 19 28 37]
[0 1 4 9]
[-5.44021111  9.12945251 -9.88031624  7.4511316 ]


array([ True,  True,  True, False])

In [68]:
#MATRIX OPERATIONS

a=np.array([[1,1],[2,2]])
b=np.array([[3,3],[4,4]])
print(a*b) #elmentwise multiplication
print()
print(a.dot(b)) #matrix mul
print(np.dot(a,b))

[[3 3]
 [8 8]]

[[ 7  7]
 [14 14]]
[[ 7  7]
 [14 14]]


In [71]:
b=np.arange(12).reshape(3,4)
print(b)
b.sum(axis=0) #sum of each column

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([12, 15, 18, 21])

In [72]:
b.sum(axis=1)#row sum

array([ 6, 22, 38])

In [74]:
#INDEXING SLICING AND ITERATING ARRAY
a=np.arange(10)**2
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [75]:
a[2:5]

array([ 4,  9, 16])

In [95]:
a[::2]


array([ 0,  4, 16, 36, 64])

In [78]:
b=np.array([[ 0, 1, 2, 3],
[10, 11, 12, 13],
[20, 21, 22, 23],
[30, 31, 32, 33],
[40, 41, 42, 43]])

b[2,3]

23

In [80]:
b[:,3]

array([ 3, 13, 23, 33, 43])

In [82]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [88]:
for i in b.flat:#shows all elements of b in 1 d array
    print(i) 

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [96]:
#changing shape of a matrix
b=np.arange(20).reshape(5,4)
print(b)
b.reshape(4,5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [98]:
#stacking in different ways
A1=np.array([(3,4,5),(12,6,1)])
A2=np.array([(1,2,6),(-4,3,8)])
d1=np.vstack((A1,A2))#vertical stack
d1

array([[ 3,  4,  5],
       [12,  6,  1],
       [ 1,  2,  6],
       [-4,  3,  8]])

In [102]:
d2=np.hstack((A1,A2))
d2 #horizontal stack

array([[ 3,  4,  5,  1,  2,  6],
       [12,  6,  1, -4,  3,  8]])

In [103]:
#stacking 1d array into 2d array
a = np.array([4.,2.])
b = np.array([3.,8.])
np.column_stack((a,b)) #2d 

array([[4., 3.],
       [2., 8.]])

In [105]:
np.hstack((a,b))

array([4., 2., 3., 8.])

In [106]:
np.vstack((a,b))

array([[4., 2.],
       [3., 8.]])

In [111]:
np.hstack((a[:,-1]),b[:,-1])

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [116]:
#indexing with array of indices

np.array([[1,2,3],[4,5,6]])[1,1]

5

In [123]:
#for mapping by vlaue:
ab=np.array([(1,2,3,4),(5,6,7,8)])
sum1=0
for i in ab:
    for j in i:
        sum1=sum1+j
sum1

36

In [130]:
sum2=0
for i in range(len(ab)):
    for j in range(len(ab[i])):
        sum2=sum2+ab[i,j]
sum2

36

# Lab Exerceises
## Q1

In [134]:
a=int(input("enter no "))
print("factors of ",a,"are:")
for i in range(2,a):
    if(a%i==0):
        print(i)

enter no 12
factors of  12 are:
2
3
4
6


## Q2


## Q3


## Q4


In [149]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,0,1,2]])
print(a)
x=np.array(a[:,0])
for i in range(1,a.shape[1]):
    x=np.vstack((x,a[:,i]))
print('\ntranspose is\n',x)

[[1 2 3 4]
 [5 6 7 8]
 [9 0 1 2]]

transpose is
 [[1 5 9]
 [2 6 0]
 [3 7 1]
 [4 8 2]]


## Q5


In [135]:
a=np.array([1,2,3,4])
b=np.array([4,3,2,1])
a+b

array([5, 5, 5, 5])

## Q6


In [139]:
a=np.array([[1,2],[5,6]])
b=np.array([[4,3],[8,7]])
a*b

array([[ 4,  6],
       [40, 42]])