### LAB 3
### HRITIK BANSAL
### CSE A 15, 180905105

# Practice Questions


In [3]:
import numpy as np
a=np.array([1,2,3,4,5])
a.dtype


dtype('int64')

In [4]:
b=np.array([1.2,22,3.445,6])
b.dtype

dtype('float64')

In [7]:
a=np.array([(1,2,3),(4,5,6)])
a #two dimentional array

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
s=np.arange(10,20,2)
s #STARTING STEPSIZE THEN ENDING LIMIT, NOT INCLUDED

array([10, 12, 14, 16, 18])

In [14]:
s=np.arange(1,2,0.1)
s

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [16]:
s1=np.linspace(10,20,7) # produce 7 numbers starting 10 & ends with 20
s1

array([10.        , 11.66666667, 13.33333333, 15.        , 16.66666667,
       18.33333333, 20.        ])

In [23]:
import random as r
r.choice([1,2,3,4,5])



5

In [20]:
r.choice("hritik")

'r'

In [22]:
r.randrange(12,45)

44

In [24]:
r.random()

0.18551823844764936

In [26]:
r.uniform(5,10)

8.062443419906774

In [30]:
c=[1,2,3,4,5]
r.shuffle(c)
c

[1, 3, 5, 2, 4]

In [39]:
a=r.seed(10)
print(a)

None


In [45]:
#2d matrix
a=np.arange(15)
print(a)
print("\n2 d\n")
a=a.reshape(3,5)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

2 d

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [50]:
#3d matrix
c=np.arange(24).reshape(2,3,4)
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [54]:
# array operations
a=np.array([10,20,30,40])
b=np.arange(4)
print(b)
c=a-b
print(c)

print(b**2)

print(10*np.sin(a))

a<35


[0 1 2 3]
[10 19 28 37]
[0 1 4 9]
[-5.44021111  9.12945251 -9.88031624  7.4511316 ]


array([ True,  True,  True, False])

# Lab Exerceises
## Q1

## Q2


## Q3


## Q4


## Q5


## Q6
